version: '3'

services:
  backend:
    container_name: fr-association-api-container
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./fr-association-api-volume:/usr/src/app
    networks:
      - backend
      - frontend

  database:
    container_name: fr-association-database-container
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./fr-association-database-volume:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - backend

volumes:
  fr-association-database-volume:
  fr-association-api-volume:

networks:
  backend:
  frontend:
